networks:
  yabinpp-network:
    name: yabinpp-network
    ipam:
      driver: default

services:
  yabinpp:
    image: ghcr.io/iidgg/yabinpp
    ports:
      - 3000:3000/tcp
    environment:
      - DATABASE_URL=postgres://john:password@db/yabinpp
      - PUBLIC_URL=https://example.com # No trailing slash
    networks:
      - yabinpp-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    healthcheck:
      interval: 5s
      timeout: 2s
      test: pg_isready -U ${DB_USER:-yabinpp_user} -d ${DB_NAME:-yabinpp_db}
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=yabinpp
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - yabinpp-network
